services:
  db:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dj-oidc-provider
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  flower:
    image: mher/flower
    container_name: flower
    restart: unless-stopped
    environment:
      - FLOWER_BASIC_AUTH=flower:123
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  postgres_data:
