services:
  django:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    command: web
    env_file:
      - .envs/.production/.django
      - .envs/.production/.postgres
    depends_on:
      - postgres
      - redis
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/vol/web/media

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles:ro
      - media_volume:/vol/web/media:ro
      - ./compose/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - django

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/.production/.postgres

  redis:
    image: redis:7

  celeryworker:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    command: worker
    env_file:
      - .envs/.production/.django
      - .envs/.production/.postgres
    depends_on:
      - redis

  celerybeat:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    command: beat
    env_file:
      - .envs/.production/.django
      - .envs/.production/.postgres
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    command: flower
    env_file:
      - .envs/.production/.django
    depends_on:
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
