services:
  django:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: django-oidc-provider__django_production
    command: /start.sh
    depends_on:
      - postgres
      - redis
    env_file:
      - .envs/.production/.django
      - .envs/.production/.postgres

  celeryworker:
    image: django-oidc-provider__django_production
    command: /start-celeryworker.sh
    depends_on:
      - django
      - redis
    env_file:
      - .envs/.production/.django
      - .envs/.production/.postgres

  celerybeat:
    image: django-oidc-provider__django_production
    command: /start-celerybeat.sh
    depends_on:
      - django
      - redis
    env_file:
      - .envs/.production/.django
      - .envs/.production/.postgres

  celeryflower:
    image: django-oidc-provider__django_production
    command: /start-celeryflower.sh
    depends_on:
      - django
      - redis
    env_file:
      - .envs/.production/.django
      - .envs/.production/.postgres

  postgres:
    image: docker.io/postgres:15
    env_file:
      - .envs/.production/.postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data

  redis:
    image: docker.io/redis:7
    volumes:
      - production_redis_data:/data

  nginx:
    image: docker.io/nginx:1.25
    ports:
      - "80:80"
      - "5555:5555"
    volumes:
      - ./compose/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
      - celeryflower

volumes:
  production_postgres_data:
  production_redis_data:
