services:
  django:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: django-oidc-provider__django_production
    depends_on:
      - postgres
      - redis
    env_file:
      - .envs/.production/.django
      - .envs/.production/.postgres
    ports:
      - "8000:8000"

  postgres:
    image: docker.io/postgres:15
    env_file:
      - .envs/.production/.postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data

  redis:
    image: docker.io/redis:7
    volumes:
      - production_redis_data:/data

volumes:
  production_postgres_data:
  production_redis_data:
